# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20170126_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='subvencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Subvencion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='rbd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contabilidadhijo',
            name='contabilidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Contabilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctipo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='contabilidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Contabilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='contabilidadhijo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.ContabilidadHijo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='doc_detalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='doc_fecha',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='doc_fecha_pago',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='doc_monto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='doc_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='doc_tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.DocTipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='gasto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='proveedor_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='proveedor_rut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Subcategoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastodetalle',
            name='deposito_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gastodetalle',
            name='fecha',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastodetalle',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='centro_costo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.CentroCosto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendicion',
            name='locked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='mes_gasto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='subvencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Subvencion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendicion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendicionesfondosdetalles',
            name='fondos_detalles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.FondoDetalle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipoformapago',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userscentrocostos',
            name='centro_costo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.CentroCosto'),
            preserve_default=False,
        ),
    ]
