# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_rendicion_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='locked',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
