# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rendicion_tipo_fondo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendicion',
            name='tipo_fondo',
        ),
    ]
