# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_rendicion_tipo_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='tipo_fondo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.TipoFondo'),
            preserve_default=False,
        ),
    ]
