# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rendicion_tipo_fondo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fondodetalle',
            old_name='contabilidadhijo',
            new_name='contabilidad_hijo',
        ),
        migrations.AddField(
            model_name='fondodetalle',
            name='doc_no_cheque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
